name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Use latest Rust stable release
        run: rustup update stable
      - name: Add support for WASM to rust toolchain.
        run: rustup target add wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install trunk
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --verbose
      - name: Build WebApp and Deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          cd html-to-seed-web
          npm ci
          trunk build --release
          npx --package=netlify-cli --yes -- netlify deploy --dir=../dist --prod
